default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  username: <%= ENV.fetch("POSTGRES_USER", "postgres") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "password") %>
  host: <%= ENV.fetch("POSTGRES_HOST", "postgres") %>
  port: <%= ENV.fetch("POSTGRES_PORT", 5432) %>

development:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB", "task_manager_development") %>

test:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_TEST_DB", "task_manager_test") %>

production:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB", "task_manager_production") %>
